path : '/content/drive/My Drive/Kifiya_AI_mastery_10_Academy/Week12/YOLOv8/data'
train: images/train
val: images/train

names:
  0: Cosmetics
  1: Nutritional Product
  2: Pharmaceutical Product
  3: Health Supplement

